### ISSUE TITLE
hotfix for classification examples

### ISSUE THREAD

**Issue by carlos-aguero** [RidgeRun/gst-inference#209]

**Comment by GFallasRR** [comment]
Adding issue information, this issue appears on Greivin's host machine
--------------------------------------------------------------------------------------------------- 
Making all in examples
make[3]: Entering directory '/home/gfallas/gst-inference/tests/examples'
Making all in classification
make[4]: Entering directory '/home/gfallas/gst-inference/tests/examples/classification'
  CC       gstclassification.o
In file included from /usr/include/glib-2.0/glib-unix.h:29:0,
                 from gstclassification.c:19:
/usr/include/x86_64-linux-gnu/sys/wait.h:101:3: error: redeclaration of enumerator ‘P_ALL’
   P_ALL,  /* Wait for any child.  */
   ^
In file included from /usr/include/x86_64-linux-gnu/sys/wait.h:35:0,
                 from /usr/include/glib-2.0/glib-unix.h:29,
                 from gstclassification.c:19:
/usr/include/x86_64-linux-gnu/bits/waitflags.h:52:3: note: previous definition of ‘P_ALL’ was here
   P_ALL,  /* Wait for any child.  */
   ^
In file included from /usr/include/glib-2.0/glib-unix.h:29:0,
                 from gstclassification.c:19:
/usr/include/x86_64-linux-gnu/sys/wait.h:102:3: error: redeclaration of enumerator ‘P_PID’
   P_PID,  /* Wait for specified process.  */
   ^
In file included from /usr/include/x86_64-linux-gnu/sys/wait.h:35:0,
                 from /usr/include/glib-2.0/glib-unix.h:29,
                 from gstclassification.c:19:
/usr/include/x86_64-linux-gnu/bits/waitflags.h:53:3: note: previous definition of ‘P_PID’ was here
   P_PID,  /* Wait for specified process.  */
   ^
In file included from /usr/include/glib-2.0/glib-unix.h:29:0,
                 from gstclassification.c:19:
/usr/include/x86_64-linux-gnu/sys/wait.h:103:3: error: redeclaration of enumerator ‘P_PGID’
   P_PGID  /* Wait for members of process group.  */
   ^
In file included from /usr/include/x86_64-linux-gnu/sys/wait.h:35:0,
                 from /usr/include/glib-2.0/glib-unix.h:29,
                 from gstclassification.c:19:
/usr/include/x86_64-linux-gnu/bits/waitflags.h:54:3: note: previous definition of ‘P_PGID’ was here
   P_PGID  /* Wait for members of process group.  */
   ^
In file included from /usr/include/glib-2.0/glib-unix.h:29:0,
                 from gstclassification.c:19:
/usr/include/x86_64-linux-gnu/sys/wait.h:104:3: error: conflicting types for ‘idtype_t’
 } idtype_t;
   ^
In file included from /usr/include/x86_64-linux-gnu/sys/wait.h:35:0,
                 from /usr/include/glib-2.0/glib-unix.h:29,
                 from gstclassification.c:19:
/usr/include/x86_64-linux-gnu/bits/waitflags.h:55:3: note: previous declaration of ‘idtype_t’ was here
 } idtype_t;
   ^
Makefile:535: recipe for target 'gstclassification.o' failed
make[4]: *** [gstclassification.o] Error 1
