### ISSUE TITLE
WARNING: erroneous pipeline: no element "detectionoverlay"

### ISSUE THREAD

**Issue by Harishrelysys** [RidgeRun/gst-inference#216]
Hi all,
I installed r2inference and gst-inference to my custom board when i run below example i am getting error

command:
========

```
CAMERA='/dev/video0'
MODEL_LOCATION='/home/root/TinyYoloV2_TensorFlow/graph_tinyyolov2_tensorflow.pb'
INPUT_LAYER='input/Placeholder'
OUTPUT_LAYER='add_8'
LABELS='/home/root/TinyYoloV2_TensorFlow/labels.txt'
gst-launch-1.0 \
v4l2src device=$CAMERA ! "video/x-raw, width=1280, height=720" ! tee name=t \
t. ! videoconvert ! videoscale ! queue ! net.sink_model \
t. ! queue ! net.sink_bypass \
tinyyolov2 name=net model-location=$MODEL_LOCATION backend=tensorflow backend::input-layer=input/Placeholder backend::output-layer=add_8 \
net.src_bypass ! videoconvert ! detectionoverlay labels="$(cat $LABELS)" font-scale=1 thickness=2 ! videoconvert ! xvimagesink sync=false
```
error:
====

> WARNING: erroneous pipeline: no element "detectionoverlay"

**Comment by jakew009** [comment]
Same problem here :/

**Comment by michaelgruner** [comment]
Hi, overlay elements will only build if OpenCV was detected on your system. Can you check your config.log and see if that is the case? This file can be very cluttered, maybe it’s easier if you reconfigure the project and look for the line that checks for OpenCV development files.

If this is the case, install libopencv-dev 

There are further instructions here:
https://developer.ridgerun.com/wiki/index.php?title=GstInference/Getting_started/Building_the_plugin

**Comment by jakew009** [comment]
Hey Michael,

Yes you are absolutely right, I figured it out shortly after commenting above, and was about to come back and explain the solution :)
The docs (hidden away at the bottom of this page: https://developer.ridgerun.com/wiki/index.php?title=GstInference/Overlay_Elements) say you need OpenCV >= 3.3.1 but it seems to work absolutely fine with the version that's bundled with Ubuntu 19.04 (3.2.0)

@michaelgruner while I have your attention :), how do I get in touch with Ridge Run? I sent an email via your contact form last week inquiring about some consulting / plugin licensing, but don't think I have had a response. Thanks

**Comment by carlos-aguero** [comment]
Hi @jakew009, best way to get in touch with RidgeRun is to send an email to support@ridgerun.com 

You can also use this wiki: [RidgeRun Contact Us](https://developer.ridgerun.com/wiki/index.php?title=GstInference/Contact_us)
