### ISSUE TITLE
example files not LGPL

### ISSUE THREAD

**Issue by boxerab** [RidgeRun/gst-inference#231]
example files are still under a proprietary license, but the project license is LGPL. Is there a plan to migrate these files to LGPL ?

**Comment by DavidSoto** [comment]
Yes, this is a mistake. @tvlenin will update it to be LGPL, generate the PR and merge the changes.

**Comment by boxerab** [comment]
great, thanks!

**Comment by rrcarlosrodriguez** [comment]
Fixed by #237
