### ISSUE TITLE
Question: how can we create new models ?

### ISSUE THREAD

**Issue by boxerab** [RidgeRun/gst-inference#239]
How are the models in the [model zoo](https://developer.ridgerun.com/wiki/index.php?title=GstInference/Model_Zoo) generated ?  Can [these](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) models be converted to run with gst-inference ?

Thanks!

**Comment by michaelgruner** [comment]
They are standard Tensorflow frozen binary graphs. So yes, every model in the Tensorflow zoo should be usable. We have documented the steps to freeze a graph in our R2I wiki: [https://developer.ridgerun.com/wiki/index.php?title=R2Inference/Supported_backends/TensorFlow#Generating_a_model_for_R2I Generating a TF model for R2I].

**Comment by michaelgruner** [comment]
Just checked the TF Zoo, looks like all the networks already provide a frozen version of the model. Look for the one suffixed as `.pb`. For example, I downloaded `ssd_mobilenet_v1_coco_2018_01_28` and inside I just found `frozen_inference_graph.pb`, which is what you'd use with GstInference.

**Comment by boxerab** [comment]
Perfect, thanks!
