### ISSUE TITLE
Prediction Memory Leak if Bypass and Model pads are used

### ISSUE THREAD

**Issue by dsteger** [RidgeRun/gst-inference#318]
If both the model and bypass pads are used the prediction data is leaked. Linked below you will notice a "goto out" jump if bypass is present which skips the prediction free. 

https://github.com/RidgeRun/gst-inference/blob/master/gst-libs/gst/r2inference/gstvideoinference.c#L972

**Comment by rrcarlosrodriguez** [comment]
Hi @dsteger ,

Thanks for your report, we will check this and get back to you.

**Comment by rrcarlosrodriguez** [comment]
Fix included in release [v0.10.1](https://github.com/RidgeRun/gst-inference/releases/tag/v0.10.1)
