### ISSUE TITLE
Check for a GoogLeNet and TinyYolo model that has the same characteristics as paper - OneDay

### ISSUE THREAD

**Issue by carlos-aguero** [RidgeRun/gst-inference#33]
Check for a model. One day task if not found start with design fix

**Comment by migueltaylor** [comment]
The GoogLeNet model used by caffe was Inception v1 or 2 and the one used by TensorFlow  was v4. On Inception v3 the input size was changed from 224x224 to 299x299.
Inception v2 for tensorflow can be downloaded here: https://github.com/tensorflow/models/tree/master/research/slim
