### ISSUE TITLE
create tensorflow wiki, how to build a graph that can be used.

### ISSUE THREAD

**Issue by carlos-aguero** [RidgeRun/gst-inference#55]

**Comment by carlos-aguero** [comment]
https://developer.ridgerun.com/wiki/index.php?title=GstInference/Supported_backends/TensorFlow

Still need to document required steps (more research required)

**Comment by carlos-aguero** [comment]
Fix broken link: Tensorflow Installation wiki page

**Comment by josejich** [comment]
completed in https://developer.ridgerun.com/wiki/index.php?title=GstInference/Supported_backends/TensorFlow
