### ISSUE TITLE
Improve documentation and steps

### ISSUE THREAD

**Issue by carlos-aguero** [RidgeRun/gst-inference#65]
- GstInference NCSDK, indicate that it is recommended to use Docker (explain why) @migueltaylor 
- r2i  wiki for tensorflow (similar to GstInference) can be based on NCSDK wiki. @josejich

**Comment by josejich** [comment]
implemented at :
https://developer.ridgerun.com/wiki/index.php?title=R2Inference/Supported_backends/TensorFlow
