### ISSUE TITLE
ETA for release ?

### ISSUE THREAD

**Issue by boxerab** [RidgeRun/gst-inference#66]
This sounds like a great project: may I ask when you are planning on releasing it?

**Comment by michaelgruner** [comment]
Hi @boxerab. Thanks! The first release is targeted for end of next week (February 3rd). It won't be fully featured yet, but will be the first usable version. Along with development we are working on documenting the project [in our developer's wiki](https://developer.ridgerun.com/wiki/index.php?title=GstInference). We'll keep examples and tutorials there.

I'll ping you via this thread when we tag the first release!

**Comment by boxerab** [comment]
Thanks, Michael, looking forward to the release!

**Comment by boxerab** [comment]
@michaelgruner is there a usable release yet ?  Thanks!

**Comment by boxerab** [comment]
I tried building the `dev-0.2` branch but I got this

```
configure: *** Plug-ins with dependencies that will NOT be built:
	gstinference
```

which was a bit sad to see.

**Comment by michaelgruner** [comment]
Hey @boxerab we did make a release. Master should be pointing to `v0.1.0` now. `dev-0.2` has our latest development, which for we have the rule that should always build, so you should be fine trying out that.

I suspect you are not building R2Inference. GstInference heavily depends on it. Take a look at:

https://developer.ridgerun.com/wiki/index.php?title=GstInference/Getting_started/Building_the_plugin

If you did build R2Inference, please share your `config.log` so I can help you further.

**Comment by michaelgruner** [comment]
Opened #83

**Comment by boxerab** [comment]
Thanks, I can now see the `inference` plugin with `gst-inspect`
