### ISSUE TITLE
Detection example 

### ISSUE THREAD

**Issue by carlos-aguero** [RidgeRun/gst-inference#79]
Emit signal for classification
Emit signal for detection
Example for classification
Example for detection

Signal will include: 
- respective meta
- ptr to buffer

**Comment by migueltaylor** [comment]
Done and merged to develop:
* Emit signal for classification
* Emit signal for detection

**Comment by carlos-aguero** [comment]
Currently in review

**Comment by carlos-aguero** [comment]
@michaelgruner not running at develop
