### ISSUE TITLE
R2Inference is not treated as mandatory dependency

### ISSUE THREAD

**Issue by michaelgruner** [RidgeRun/gst-inference#83]

**Comment by michaelgruner** [comment]
The configure script should fail if no R2Inference is found, instead of silently continuing.

**Comment by michaelgruner** [comment]
Closed by 5176e23aa19af7782b5bcc043ae0dc032fd27acd. @boxerab dev-0.2 should be updated. New tag expected by EOD.

**Comment by boxerab** [comment]
Great. btw, I found the dev-0.7 branch no longer runs my Inception model. I can post the stack trace if you're interested.

**Comment by michaelgruner** [comment]
@tvlenin @c-trejos let's unbreak this ASAP please

**Comment by rrcarlosrodriguez** [comment]
@boxerab please share your stack trace for reference so we can fix it ASAP

**Comment by boxerab** [comment]
actually, the crash was in gst-inference, dev-0.7 branch. I will open an issue there.
